services:
  coder:
    image: codercom/code-server:${CODE_SERVER_VERSION:?}
    container_name: code-server
    hostname: code
    # ports:
    #   - 50100:8080
    environment:
      DOCKER_USER: ${USER:?}
    restart: unless-stopped
    volumes:
      - ${HOME}/vscode/config:/home/coder/.config
      - ${HOME}/vscode/local:/home/coder/.local/share
      - ${HOME}/projects:/home/coder/projects
    user: ${UID:?}:${GID:?}
