version: '3.7'

services:
  coder:
    image: codercom/code-server:3.10.2
    container_name: code-server
    hostname: code
    # ports:
    #   - 50100:8080
    environment:
      DOCKER_USER: ${USER:?}
    restart: always
    volumes:
      - ${HOME}/.config/code-server:/home/coder/.config/code-server
      - ${HOME}/.local/share/code-server:/home/coder/.local/share/code-server
      - ${HOME}/projects:/home/coder/projects
    user: ${UID:?}:${GID:?}
