volumes:
  config:
    name: rabbitmq_config
  data:
    name: rabbitmq_data
  logs:
    name: rabbitmq_logs

networks:
  rabbitmq:
    name: rabbitmq

services:
  rabbitmq:
    image: rabbitmq:${RABBITMQ_VERSION:?}
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - ${RABBITMQ_PORT:-5672}:5672
      - ${RABBITMQ_MANAGEMENT_PORT:-15672}:15672
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER:?}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD:?}
      RABBITMQ_DEFAULT_VHOST: ${RABBITMQ_VHOST:-default}
      RABBITMQ_NODENAME: rabbit@rabbitmq
    restart: unless-stopped
    volumes:
      - config:/etc/rabbitmq
      - data:/var/lib/rabbitmq
      - logs:/var/log/rabbitmq
    networks:
      - rabbitmq
