volumes:
  mysql:
    name: mysql_data

networks:
  mysql:
    name: mysql

services:
  mysql:
    image: mysql:${MYSQL_VERSION:?}
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    container_name: mysql
    hostname: mysql
    ports:
      - ${MYSQL_PORT:-3306}:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:?}
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
      MYSQL_DATABASE: ${MYSQL_DATABASE:-db}
    restart: unless-stopped
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - mysql

  phpmyadmin:
    image: phpmyadmin:${PHPMYADMIN_VERSION:?}
    container_name: phpmyadmin
    hostname: phpmyadmin
    depends_on:
      - mysql
    ports:
      - ${PHPMYADMIN_PORT:-3307}:80
    environment:
      # PMA_ARBITRARY: $PMA_ARBITRARY
      PMA_HOST: mysql
      PMA_PORT: 3306
      # PMA_USER: root
      # PMA_PASSWORD: ${MYSQL_ROOT_PASSWORD:?}
      # PMA_USER: $MYSQL_USER
      # PMA_PASSWORD: $MYSQL_PASSWORD
      UPLOAD_LIMIT: ${UPLOAD_LIMIT:-100M}
      PMA_ABSOLUTE_URI: $PMA_ABSOLUTE_URI # https://host/path
    restart: unless-stopped
    networks:
      - mysql
