volumes:
  freshrss_data:
    name: freshrss_data
  freshrss_extensions:
    name: freshrss_extensions

networks:
  freshrss:
    name: freshrss

services:
  freshrss:
    image: freshrss/freshrss:${FRESHRSS_VERSION}
    container_name: freshrss
    hostname: freshrss
    ports:
      - ${FRESHRSS_PORT:?}:80
    environment:
      TZ: ${TZ:-Europe/Warsaw}
      CRON_MIN: "3,33"
    restart: unless-stopped
    logging:
      options:
        max-size: 10m
    volumes:
      - freshrss_data:/var/www/FreshRSS/data
      - freshrss_extensions:/var/www/FreshRSS/extensions
    networks:
      - freshrss
