volumes:
  matomo:
    name: matomo_data
  db:
    name: matomo_db_data

networks:
  matomo:
    name: matomo

services:
  matomo:
    image: matomo:${MATOMO_VERSION}
    container_name: matomo
    hostname: matomo
    depends_on:
      - db
    restart: unless-stopped
    ports:
      - ${MATOMO_PORT:?}:80
    volumes:
      - matomo:/var/www/html
      # - ./config:/var/www/html/config
    environment:
      MATOMO_DATABASE_HOST: db
      MATOMO_DATABASE_ADAPTER: mysql
      MATOMO_DATABASE_TABLES_PREFIX: ${MATOMO_DATABASE_TABLES_PREFIX:-matomo_}
      MATOMO_DATABASE_DBNAME: matomo
      MATOMO_DATABASE_USERNAME: matomo
      MATOMO_DATABASE_PASSWORD: ${MARIADB_PASSWORD:?}
    networks:
      - matomo

  db:
    image: mariadb:${MARIADB_VERSION:?}
    command: --max-allowed-packet=64MB
    container_name: matomo_mariadb
    hostname: matomo_mariadb
    restart: unless-stopped
    volumes:
      - db:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD:?}
      MARIADB_DATABASE: matomo
      MARIADB_USER: matomo
      MARIADB_PASSWORD: ${MARIADB_PASSWORD:?}
    networks:
      - matomo
