version: "3.7"

volumes:
  data:
    name: uptime_kuma_data

services:
  uptime_kuma:
    image: louislam/uptime-kuma:1
    container_name: uptime_kuma
    hostname: kuma
    environment:
      UPTIME_KUMA_PORT: ${UPTIME_KUMA_PORT:-3001}
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - data:/app/data
    network_mode: host
