version: "3.7"

volumes:
  data:
    name: uptime_kuma_data

networks:
  uptime_kuma:
    name: uptime_kuma

services:
  uptime_kuma:
    image: louislam/uptime-kuma:1
    container_name: uptime_kuma
    hostname: kuma
    ports:
      - 3001:3001
    restart: always
    volumes:
      - data:/app/data
    networks:
      - uptime_kuma
