volumes:
  postgres:
    name: postgres_data

networks:
  postgres:
    name: postgres

services:
  postgres:
    image: postgres:${POSTGRES_VERSION:?}
    container_name: postgres
    hostname: postgres
    ports:
      - ${POSTGRES_PORT:-5432}:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?}
      POSTGRES_DB: ${POSTGRES_DB:-db}
    restart: unless-stopped
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - postgres

  adminer:
    image: adminer:${ADMINER_VERSION:?}
    container_name: adminer
    hostname: adminer
    depends_on:
      - postgres
    ports:
      - ${ADMINER_PORT:-8080}:8080
    environment:
      ADMINER_DESIGN: ${ADMINER_DESIGN:-nicu}
      ADMINER_DEFAULT_SERVER: postgres
    restart: unless-stopped
    networks:
      - postgres
