volumes:
  postgres:
    name: postgres_data
  pgadmin:
    name: pgadmin_data

networks:
  postgres:
    name: postgres

services:
  postgres:
    image: postgres:${POSTGRES_VERSION:?}
    container_name: postgres
    hostname: postgres
    ports:
      - ${POSTGRES_PORT:-5432}:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?}
      POSTGRES_DB: ${POSTGRES_DB:-db}
    restart: unless-stopped
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - postgres

  pgadmin:
    image: dpage/pgadmin4:${PGADMIN_VERSION:?}
    container_name: pgadmin
    hostname: pgadmin
    depends_on:
      - postgres
    ports:
      - ${PGADMIN_PORT:-8080}:80
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL:?}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD:?}
    restart: unless-stopped
    volumes:
      - pgadmin:/var/lib/pgadmin
    networks:
      - postgres
