version: "3.7"

volumes:
  mongo:
    name: mongo_data

networks:
  mongo:
    name: mongo

services:
  mongo:
    image: mongo:4.4
    container_name: mongo
    hostname: mongo
    ports:
      - ${MONGO_PORT:-27017}:8081
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_LOGIN:?}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD:?}
    restart: always
    volumes:
      - mongo:/data/db
    networks:
      - mongo

  mongo_express:
    image: mongo-express:0.54
    container_name: mongo_express
    hostname: mongo_express
    depends_on:
      - mongo
    ports:
      - ${MONGO_EXPRESS_PORT:-27018}:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_ROOT_LOGIN:?}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_ROOT_PASSWORD:?}
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_EXPRESS_LOGIN:-}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_EXPRESS_PASSWORD:-}
      ME_CONFIG_SITE_BASEURL: ${MONGO_EXPRESS_BASE_URL:-/}
      ME_CONFIG_REQUEST_SIZE: 100mb
    restart: always
    networks:
      - mongo
