version: '3.7'

volumes:
  mongo:
    name: mongo_data

networks:
  mongo:
    name: mongo

services:
  mongo:
    image: mongo:4.4
    container_name: mongo
    hostname: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: '${MONGODB_ROOT_LOGIN:?}'
      MONGO_INITDB_ROOT_PASSWORD: '${MONGODB_ROOT_PASSWORD:?}'
    restart: always
    volumes:
      - mongo:/data/db
    networks:
      - mongo

  mongo_gui:
    image: mongo-express:0.54
    container_name: mongo_express
    hostname: mongo
    depends_on:
      - mongo
    ports:
      - 27018:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: '${MONGODB_GUI_LOGIN:?}'
      ME_CONFIG_BASICAUTH_PASSWORD: '${MONGODB_GUI_PASSWORD:?}'
      ME_CONFIG_MONGODB_ADMINUSERNAME: '${MONGODB_ROOT_LOGIN:?}'
      ME_CONFIG_MONGODB_ADMINPASSWORD: '${MONGODB_ROOT_PASSWORD:?}'
      ME_CONFIG_MONGODB_SERVER: 'mongo.mongo'
      ME_CONFIG_SITE_BASEURL: '/mongodb/'
    restart: always
    networks:
      - mongo
